-- Manual RLS check. Run against a seeded database:
--
--   supabase db reset            -- applies migrations + seed.sql
--   psql "$(supabase status -o env | grep DB_URL | cut -d= -f2-)" -f supabase/tests/rls_smoke.sql
--
-- It impersonates a user by setting the same JWT claims PostgREST sets, so
-- auth.uid() — and therefore every policy — behaves exactly as it does for the
-- app. Each block raises if the count is wrong, so a leak fails loudly.
--
-- The seed ships one factory. A second one is created here, inside the
-- transaction, purely to prove the tenant boundary — the closing ROLLBACK means
-- neither it nor its logins ever exist outside this script.

begin;

-- --- Second tenant, for this transaction only --------------------------------
-- Runs as the connecting superuser, before any role switch, so RLS does not
-- apply to the setup itself.

insert into factories (id, name) values
  ('22222222-2222-2222-2222-222222222222', 'Test Factory B');

insert into auth.users (
  id, instance_id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data
)
values
  ('bbbbbbb2-0000-4000-8000-000000000001', '00000000-0000-0000-0000-000000000000',
   'authenticated', 'authenticated', 'taker.b@example.test',
   crypt('password123', gen_salt('bf')), now(), now(), now(),
   '{"provider":"email","providers":["email"]}', '{}'),
  ('bbbbbbb2-0000-4000-8000-000000000002', '00000000-0000-0000-0000-000000000000',
   'authenticated', 'authenticated', 'qa.b@example.test',
   crypt('password123', gen_salt('bf')), now(), now(), now(),
   '{"provider":"email","providers":["email"]}', '{}');

insert into profiles (id, factory_id, role, full_name) values
  ('bbbbbbb2-0000-4000-8000-000000000001', '22222222-2222-2222-2222-222222222222', 'order_taker', 'Order Taker B'),
  ('bbbbbbb2-0000-4000-8000-000000000002', '22222222-2222-2222-2222-222222222222', 'qa_person',   'QA B');

insert into clients (id, factory_id, name, phone) values
  ('c2222222-0000-4000-8000-000000000001', '22222222-2222-2222-2222-222222222222', 'Factory B Client', '03007654321');

insert into orders (id, factory_id, code, client_id, status, stage) values
  ('02222222-0000-4000-8000-000000000001', '22222222-2222-2222-2222-222222222222',
   'TFB-0001', 'c2222222-0000-4000-8000-000000000001', 'in_progress', 'inspection');

-- The fan-out trigger turns this into 4 pending inspection_units.
insert into order_sheets (id, order_id, color_id, repeats) values
  ('52222222-0000-4000-8000-000000000001', '02222222-0000-4000-8000-000000000001', 'green', 4);

set local role authenticated;

-- --- Factory A, order taker -------------------------------------------------
set local request.jwt.claims = '{"sub":"aaaaaaa1-0000-4000-8000-000000000001","role":"authenticated"}';

do $$
declare n int;
begin
  select count(*) into n from orders;
  if n <> 1 then
    raise exception 'Factory A taker should see exactly 1 order, saw %', n;
  end if;

  select count(*) into n from orders where code = 'TFB-0001';
  if n <> 0 then
    raise exception 'LEAK: Factory A taker can read Factory B orders';
  end if;

  select count(*) into n from clients;
  if n <> 1 then
    raise exception 'Factory A taker should see exactly 1 client, saw %', n;
  end if;

  -- 3 + 2 repeats, generated by the fan-out trigger.
  select count(*) into n from inspection_units;
  if n <> 5 then
    raise exception 'Fan-out should have produced 5 units for Factory A, saw %', n;
  end if;
end $$;

-- --- Factory B, QA person ---------------------------------------------------
set local request.jwt.claims = '{"sub":"bbbbbbb2-0000-4000-8000-000000000002","role":"authenticated"}';

do $$
declare n int;
begin
  select count(*) into n from orders;
  if n <> 1 then
    raise exception 'Factory B QA should see exactly 1 order, saw %', n;
  end if;

  select count(*) into n from orders where code = 'ARE-0001';
  if n <> 0 then
    raise exception 'LEAK: Factory B QA can read Factory A orders';
  end if;

  select count(*) into n from inspection_units;
  if n <> 4 then
    raise exception 'Factory B QA should see 4 units, saw %', n;
  end if;
end $$;

-- --- Role boundaries --------------------------------------------------------

-- QA may update a unit in its own factory.
do $$
declare n int;
begin
  update inspection_units set status = 'passed', passed_code = 'B-01'
  where order_id = '02222222-0000-4000-8000-000000000001'
    and repeat_index_in_sheet = 1;

  get diagnostics n = row_count;
  if n <> 1 then
    raise exception 'Factory B QA should be able to pass its own unit, updated % rows', n;
  end if;
end $$;

-- QA may not create orders (no insert policy for that role).
do $$
begin
  insert into orders (factory_id, code, client_id)
  values ('22222222-2222-2222-2222-222222222222', 'TFB-9999',
          'c2222222-0000-4000-8000-000000000001');
  raise exception 'LEAK: qa_person was allowed to insert an order';
exception
  when insufficient_privilege then null;  -- expected
end $$;

-- Nobody may write into another factory.
do $$
begin
  set local request.jwt.claims = '{"sub":"aaaaaaa1-0000-4000-8000-000000000001","role":"authenticated"}';
  insert into orders (factory_id, code, client_id)
  values ('22222222-2222-2222-2222-222222222222', 'ARE-9999',
          'c1111111-0000-4000-8000-000000000001');
  raise exception 'LEAK: Factory A taker inserted an order into Factory B';
exception
  when insufficient_privilege then null;  -- expected
end $$;

-- Discards the second tenant along with everything the checks touched.
rollback;
